### PR TITLE
Added Capstone/Tile Count in Canvas

### PR DESCRIPTION
**Pull request by Pixelmation**
Added a new Capstone Counter under controls. Call to change the text field is in TileFactory.cs with a public reference to the text object.

### CODE REVIEW

**Review by saporter — CHANGES_REQUESTED** [review]
I'm sure it's great but another PR came in just before yours that's conflicting with your merge.. Do you think you could help me resolve it?  Conflicts are Sample Scene and TileFactory.cs

**Comment by Pixelmation** [comment]
Of course, I'll pull the change and fix it my end, then push it again. should be a quick fix

**Comment by Pixelmation** [comment]
Apologies but it seems there's still an issue and I'm not sure what it is. I fixed the changes as far as I can tell from my branch, rebasing to take the conflict from the other merge and go through and manually accept the proper merge for each conflict. However, the conflicting changes don't seem to be actually fixed according to the repo here and the merge is blocked, and yet I can't seem to figure out why

**Comment by Pixelmation** [comment]
As far as I can tell, any actual changes are just unity being difficult and I can't tell why. The conflict is a new scene added by Silvia and a new script, neither of which are related to my changes in the samplescene or tilefactory.cs

**Review by saporter — APPROVED** [review]

**Comment by saporter** [comment]
Yeah I've re-cloned the repo to rebuild from scratch and I still can't get it to work.  It complains about missing scripts plus some strange errors I've never seen before.. perhaps you can diagnose better than I can?  

Try re-cloning dev on your end and see if you get the same errors I do (ensure you delete everything in your working folder to have Unity rebuild from scratch).

**Pull request merged**
